services:
  gold-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    image: gold-monitor:latest
    container_name: gold-monitor
    ports:
      - "20031:8081"
    environment:
      - TZ=Asia/Shanghai
      - GIN_MODE=release
    deploy:
      resources:
        limits:
          memory: 64M
    network_mode: bridge
    restart: always
